export const CHANGE_SEARCH_INPUT = 'CHANGE_SEARCH_INPUT';

export const RECEIVE_WEATHER_INFO = 'RECEIVE_WEATHER_INFO';
export const RECEIVE_FORECAST_INFO = 'RECEIVE_FORECAST_INFO';
export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';
