export const GEO_REQUEST_SUCCEEDED = 'GEO_REQUEST_SUCCEEDED';

export const CHANGE_SEARCH_INPUT = 'CHANGE_SEARCH_INPUT';

export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const FORECAST_REQUEST = 'FORECAST_REQUEST';

export const WEATHER_REQUEST_FAILED = 'WEATHER_REQUEST_FAILED';
export const FORECAST_REQUEST_FAILED = 'FORECAST_REQUEST_FAILED';

export const RECEIVED_WEATHER_INFO = 'RECEIVED_WEATHER_INFO';
export const RECEIVED_FORECAST_INFO = 'RECEIVED_FORECAST_INFO';

